// modify this to add new theme property
export const themeProps = {
    "--body-bg-color": "主体背景色",
    "--topBar-color": "顶部栏背景色",
    "--icon-color": "图标颜色",
    "--font-color": "文本颜色",
    "--font-color-secondary": "次级文本颜色",
    "--font-select-color": "选中文本颜色",
    "--font-select-bg-color": "选中文本背景色",
    "--btn-color": "按钮颜色",
    "--btn-color-hover": "按钮悬停颜色",
    "--btn-color-focus": "按钮聚焦颜色",
    "--btn-shadow-focus": "按钮聚焦阴影颜色",
    "--topBar-btn-hover": "顶部栏按钮悬停颜色",
    "--text-input-bg": "输入框背景色",
    "--text-input-bg-focus": "输入框聚焦背景色",
    "--listItem-bg-color": "列表项背景色",
    "--listItem-bg-color-hover": "列表项悬停背景色",
    "--listItem-bg-color-read": "已读列表项背景色",
    "--listItem-bg-color-current": "侧边列表当前项背景色",
    "--readerSettings-bg": "阅读器设置背景",
    "--readerSettings-toggleBtn-bg-color": "阅读器设置切换按钮颜色",
    "--readerSettings-toggleBtn-bg-color-hover": "阅读器设置切换按钮悬停颜色",
    "--sideList-bg-color": "阅读器侧边列表背景色",
    "--reader-sidelist-divider-color": "阅读器侧边列表分隔线颜色",
    "--scrollbar-track-color": "滚动条轨道颜色",
    "--scrollbar-thumb-color": "滚动条滑块颜色",
    "--scrollbar-thumb-color-hover": "滚动条滑块悬停颜色",
    "--code-text-color": "代码文本颜色",
    "--code-bg-color": "代码背景色",
    "--code-shadow-color": "代码阴影颜色",
    "--divider-color": "分隔线颜色",
    "--contextMenu-bg-color": "Context-Menu BG",
    "--contentMenu-item-color": "Context-Menu Item BG",
    "--contentMenu-item-bg-color-hover": "Context-Menu Item BG Hovered/Focused",
    //todo move to reader settings or add duplicate for epub
    "--zenModePage-bg": "Zen Mode 页码指示背景（仅漫画阅读器）",
};

export const initThemeData = {
    // default theme
    name: "dark1",
    allData: [
        {
            name: "dark1",
            main: {
                "--body-bg-color": "#262626ff",
                "--topBar-color": "#1f1f1fff",
                "--icon-color": "#ffffffff",
                "--font-color": "var(--icon-color)",
                "--font-color-secondary": "#999999ff",
                "--font-select-color": "#000000ff",
                "--font-select-bg-color": "#ffffffff",
                "--btn-color": "#363636ff",
                "--btn-color-hover": "#6b6b6bff",
                "--btn-color-focus": "#4f4f4fff",
                "--btn-shadow-focus": "var(--btn-color-focus)",
                "--topBar-btn-hover": "var(--btn-color-hover)",
                "--text-input-bg": "var(--btn-color)",
                "--text-input-bg-focus": "var(--btn-color-focus)",
                "--listItem-bg-color": "#00000000",
                "--listItem-bg-color-hover": "var(--btn-color)",
                "--listItem-bg-color-read": "var(--btn-color-focus)",
                "--listItem-bg-color-current": "var(--btn-color-hover)",
                "--readerSettings-bg": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color-hover": "var(--body-bg-color)",
                "--sideList-bg-color": "var(--topBar-color)",
                "--reader-sidelist-divider-color": "var(--btn-color-hover)",
                "--scrollbar-track-color": "#00000000",
                "--scrollbar-thumb-color": "var(--btn-color)",
                "--scrollbar-thumb-color-hover": "var(--btn-color-hover)",
                "--code-text-color": "var(--font-color-secondary)",
                "--code-bg-color": "var(--btn-color-hover)",
                "--code-shadow-color": "var(--btn-color)",
                "--divider-color": "var(--btn-color)",
                "--contextMenu-bg-color": "var(--body-bg-color)",
                "--contentMenu-item-color": "var(--font-color)",
                "--contentMenu-item-bg-color-hover": "var(--btn-color-focus)",
                "--zenModePage-bg": "#26262680",
            },
        },
        {
            name: "dark2",
            main: {
                "--body-bg-color": "#000000",
                "--sideList-bg-color": "var(--topBar-color)",
                "--icon-color": "#fff8f0",
                "--font-color": "#fff8f0",
                "--font-color-secondary": "#888581",
                "--font-select-color": "#000000",
                "--font-select-bg-color": "#fff8f0",
                "--btn-color": "#3b3a3e",
                "--btn-color-hover": "#62636e",
                "--btn-color-focus": "#6c6e7a",
                "--btn-shadow-focus": "var(--btn-color-focus)",
                "--text-input-bg": "#3b3a3e",
                "--text-input-bg-focus": "#62636e",
                "--topBar-color": "#17171c",
                "--topBar-btn-hover": "#62636e",
                "--listItem-bg-color": "#00000000",
                "--listItem-bg-color-hover": "#55535b",
                "--listItem-bg-color-read": "#37343f",
                "--listItem-bg-color-current": "#585a70",
                "--readerSettings-bg": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color-hover": "#62636e",
                "--scrollbar-track-color": "#00000000",
                "--scrollbar-thumb-color": "#545454",
                "--scrollbar-thumb-color-hover": "#878787",
                "--code-text-color": "var(--font-color-secondary)",
                "--code-bg-color": "var(--btn-color)",
                "--code-shadow-color": "var(--btn-color)",
                "--divider-color": "#3b3a3e",
                "--reader-sidelist-divider-color": "var(--btn-color-hover)",
                "--contextMenu-bg-color": "var(--body-bg-color)",
                "--contentMenu-item-color": "var(--font-color)",
                "--contentMenu-item-bg-color-hover": "var(--btn-color-focus)",
                "--zenModePage-bg": "#00000080",
            },
        },
        {
            name: "dark3",
            main: {
                "--body-bg-color": "#000000ff",
                "--topBar-color": "#17171cff",
                "--icon-color": "#fff8f0ff",
                "--font-color": "#fff8f0ff",
                "--font-color-secondary": "#808080ff",
                "--font-select-color": "#000000ff",
                "--font-select-bg-color": "#fff8f0ff",
                "--btn-color": "#1b1b1dff",
                "--btn-color-hover": "#36363aff",
                "--btn-color-focus": "#4e4e55ff",
                "--btn-shadow-focus": "var(--btn-color-focus)",
                "--topBar-btn-hover": "var(--btn-color-focus)",
                "--text-input-bg": "var(--btn-color)",
                "--text-input-bg-focus": "var(--btn-color-focus)",
                "--listItem-bg-color": "#00000000",
                "--listItem-bg-color-hover": "var(--btn-color-hover)",
                "--listItem-bg-color-read": "var(--btn-color-focus)",
                "--listItem-bg-color-current": "var(--btn-color-focus)",
                "--readerSettings-bg": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color-hover": "var(--btn-color-hover)",
                "--sideList-bg-color": "var(--topBar-color)",
                "--reader-sidelist-divider-color": "var(--btn-color-hover)",
                "--scrollbar-track-color": "#00000000",
                "--scrollbar-thumb-color": "var(--btn-color)",
                "--scrollbar-thumb-color-hover": "var(--btn-color-hover)",
                "--code-text-color": "var(--font-color-secondary)",
                "--code-bg-color": "var(--btn-color-hover)",
                "--code-shadow-color": "var(--btn-color)",
                "--divider-color": "var(--topBar-color)",
                "--contextMenu-bg-color": "var(--body-bg-color)",
                "--contentMenu-item-color": "var(--font-color)",
                "--contentMenu-item-bg-color-hover": "var(--btn-color-focus)",
                "--zenModePage-bg": "#00000080",
            },
        },
        {
            name: "light1",
            main: {
                "--body-bg-color": "#ffffff",
                "--sideList-bg-color": "var(--topBar-color)",
                "--icon-color": "#000c29",
                "--font-color": "#000c29",
                "--font-color-secondary": "#6b758e",
                "--font-select-color": "#fff8f0",
                "--font-select-bg-color": "#000c29",
                "--btn-color": "#b6ccfe",
                "--btn-color-hover": "#709bff",
                "--btn-color-focus": "#8aadff",
                "--btn-shadow-focus": "var(--btn-color-focus)",
                "--text-input-bg": "#b6ccfe",
                "--text-input-bg-focus": "#709bff",
                "--topBar-color": "#e0e0e0",
                "--topBar-btn-hover": "#b6ccfe",
                "--listItem-bg-color": "#00000000",
                "--listItem-bg-color-hover": "#b6ccfe",
                "--listItem-bg-color-read": "#d0dcff",
                "--listItem-bg-color-current": "#709bff",
                "--readerSettings-bg": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color-hover": "#709bff",
                "--scrollbar-track-color": "#b6ccfe00",
                "--scrollbar-thumb-color": "#b6ccfe",
                "--scrollbar-thumb-color-hover": "#709bff",
                "--code-text-color": "var(--font-color)",
                "--code-bg-color": "var(--btn-color-hover)",
                "--code-shadow-color": "var(--btn-color)",
                "--divider-color": "#b6ccfe",
                "--reader-sidelist-divider-color": "var(--btn-color-hover)",
                "--contextMenu-bg-color": "var(--body-bg-color)",
                "--contentMenu-item-color": "var(--font-color)",
                "--contentMenu-item-bg-color-hover": "var(--btn-color-focus)",
                "--zenModePage-bg": "#ffffff90",
            },
        },
        {
            name: "light2",
            main: {
                "--body-bg-color": "#ffffffff",
                "--topBar-color": "#e0e0e0ff",
                "--icon-color": "#000c29ff",
                "--font-color": "#000c29ff",
                "--font-color-secondary": "#4d4d4dff",
                "--font-select-color": "#fff8f0ff",
                "--font-select-bg-color": "#000c29ff",
                "--btn-color": "#e6e6e6ff",
                "--btn-color-hover": "#ccccccff",
                "--btn-color-focus": "#b3b3b3ff",
                "--btn-shadow-focus": "var(--btn-color-focus)",
                "--topBar-btn-hover": "var(--btn-color-hover)",
                "--text-input-bg": "var(--btn-color)",
                "--text-input-bg-focus": "var(--btn-color-focus)",
                "--listItem-bg-color": "#00000000",
                "--listItem-bg-color-hover": "var(--btn-color)",
                "--listItem-bg-color-read": "var(--btn-color-hover)",
                "--listItem-bg-color-current": "var(--btn-color-focus)",
                "--readerSettings-bg": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color": "var(--body-bg-color)",
                "--readerSettings-toggleBtn-bg-color-hover": "var(--btn-color-focus)",
                "--sideList-bg-color": "var(--topBar-color)",
                "--reader-sidelist-divider-color": "var(--btn-color-hover)",
                "--scrollbar-track-color": "#e6e6e600",
                "--scrollbar-thumb-color": "var(--btn-color)",
                "--scrollbar-thumb-color-hover": "var(--btn-color-hover)",
                "--code-text-color": "var(--font-color-secondary)",
                "--code-bg-color": "var(--btn-color-hover)",
                "--code-shadow-color": "var(--btn-color)",
                "--divider-color": "var(--topBar-color)",
                "--contextMenu-bg-color": "var(--body-bg-color)",
                "--contentMenu-item-color": "var(--font-color)",
                "--contentMenu-item-bg-color-hover": "var(--btn-color-focus)",
                "--zenModePage-bg": "#ffffff90",
            },
        },
    ],
} satisfies {
    name: string;
    allData: ThemeData[];
};
